.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "NACK" "1" "November 2010" "" ""
.
.SH "NAME"
\fBnack\fR \- node powered rack server
.
.SH "SYNOPSIS"
\fBnack\fR [\fIconfig\fR] [\fIport\fR]
.
.SH "DESCRIPTION"
Starts nack server with rackup config on port\. If no port is given, it defaults to 3000\.
.
.SH "SEE ALSO"
nack\-server(3)
