// Generated by CoffeeScript 1.6.2
(function() {
  var createPool, createServer;

  createServer = require('http').createServer;

  createPool = require('./pool').createPool;

  exports.createServer = function(config, options) {
    var pool, _ref, _ref1;

    if (options == null) {
      options = {};
    }
    if ((_ref = options.size) == null) {
      options.size = 3;
    }
    if ((_ref1 = options.idle) == null) {
      options.idle = 15 * 60 * 1000;
    }
    pool = createPool(config, options);
    return createServer(pool.proxy);
  };

}).call(this);
