// Generated by CoffeeScript 1.3.3
(function() {
  var LineBuffer, Stream, debug,
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Stream = require('stream').Stream;

  if (process.env.NODE_DEBUG && /nack/.test(process.env.NODE_DEBUG)) {
    debug = exports.debug = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return console.error.apply(console, ['NACK:'].concat(__slice.call(args)));
    };
  } else {
    debug = exports.debug = function() {};
  }

  exports.isFunction = function(obj) {
    if (obj && obj.constructor && obj.call && obj.apply) {
      return true;
    } else {
      return false;
    }
  };

  exports.LineBuffer = LineBuffer = (function(_super) {

    __extends(LineBuffer, _super);

    function LineBuffer(stream) {
      var self;
      this.stream = stream;
      this.readable = true;
      this._buffer = "";
      self = this;
      this.stream.on('data', function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return self.write.apply(self, args);
      });
      this.stream.on('end', function() {
        var args;
        args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
        return self.end.apply(self, args);
      });
    }

    LineBuffer.prototype.write = function(chunk) {
      var index, line, _results;
      this._buffer += chunk;
      _results = [];
      while ((index = this._buffer.indexOf("\n")) !== -1) {
        line = this._buffer.slice(0, index);
        this._buffer = this._buffer.slice(index + 1, this._buffer.length);
        _results.push(this.emit('data', line));
      }
      return _results;
    };

    LineBuffer.prototype.end = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (args.length > 0) {
        this.write.apply(this, args);
      }
      return this.emit('end');
    };

    return LineBuffer;

  })(Stream);

  exports.BufferedPipe = (function(_super) {

    __extends(BufferedPipe, _super);

    function BufferedPipe() {
      this.writable = true;
      this.readable = true;
      this._queue = [];
      this._ended = false;
    }

    BufferedPipe.prototype.write = function(chunk, encoding) {
      if (this._queue) {
        debug("queueing " + chunk.length + " bytes");
        this._queue.push([chunk, encoding]);
      } else {
        debug("writing " + chunk.length + " bytes");
        this.emit('data', chunk, encoding);
      }
    };

    BufferedPipe.prototype.end = function(chunk, encoding) {
      if (chunk) {
        this.write(chunk, encoding);
      }
      if (this._queue) {
        this._ended = true;
      } else {
        debug("closing connection");
        this.emit('end');
      }
    };

    BufferedPipe.prototype.destroy = function() {
      return this.writable = false;
    };

    BufferedPipe.prototype.flush = function() {
      var chunk, encoding, _ref;
      if (!this._queue) {
        return;
      }
      while (this._queue && this._queue.length) {
        _ref = this._queue.shift(), chunk = _ref[0], encoding = _ref[1];
        debug("writing " + chunk.length + " bytes");
        this.emit('data', chunk, encoding);
      }
      if (this._ended) {
        debug("closing connection");
        this.emit('end');
      }
      this._queue = null;
    };

    return BufferedPipe;

  })(Stream);

  exports.BufferedRequest = (function(_super) {

    __extends(BufferedRequest, _super);

    function BufferedRequest(method, url, headers, proxyMetaVariables) {
      var _this = this;
      this.method = method;
      this.url = url;
      this.headers = headers != null ? headers : {};
      this.proxyMetaVariables = proxyMetaVariables != null ? proxyMetaVariables : {};
      BufferedRequest.__super__.constructor.apply(this, arguments);
      this.once('pipe', function(src) {
        var key, value, _base, _base1, _base2, _base3, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7, _ref8, _ref9;
        if ((_ref = _this.method) == null) {
          _this.method = src.method;
        }
        if ((_ref1 = _this.url) == null) {
          _this.url = src.url;
        }
        _ref2 = src.headers;
        for (key in _ref2) {
          value = _ref2[key];
          if ((_ref3 = (_base = _this.headers)[key]) == null) {
            _base[key] = value;
          }
        }
        _ref4 = src.proxyMetaVariables;
        for (key in _ref4) {
          value = _ref4[key];
          if ((_ref5 = (_base1 = _this.proxyMetaVariables)[key]) == null) {
            _base1[key] = value;
          }
        }
        if ((_ref6 = (_base2 = _this.proxyMetaVariables)['REMOTE_ADDR']) == null) {
          _base2['REMOTE_ADDR'] = "" + ((_ref7 = src.connection) != null ? _ref7.remoteAddress : void 0);
        }
        return (_ref8 = (_base3 = _this.proxyMetaVariables)['REMOTE_PORT']) != null ? _ref8 : _base3['REMOTE_PORT'] = "" + ((_ref9 = src.connection) != null ? _ref9.remotePort : void 0);
      });
    }

    return BufferedRequest;

  })(exports.BufferedPipe);

}).call(this);
